In [1]:
from keras.layers import Conv2D, ZeroPadding2D, Activation, Input, concatenate

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [2]:
from model import create_model
from align import AlignDlib
import os
import numpy as np
import cv2
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
import sys
from PIL import Image
sys.modules['Image'] = Image
from PIL import Image
import warnings
from scipy import ndimage
warnings.filterwarnings('ignore')

In [3]:
# Model for 128 embeddings from a image
nn4_small2_pretrained = create_model()
nn4_small2_pretrained.load_weights('weights/nn4.small2.v1.h5')

In [4]:
# Model Summary
nn4_small2_pretrained.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 96, 96, 3)    0                                            
__________________________________________________________________________________________________
zero_padding2d_1 (ZeroPadding2D (None, 102, 102, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 48, 48, 64)   9472        zero_padding2d_1[0][0]           
__________________________________________________________________________________________________
bn1 (BatchNormalization)        (None, 48, 48, 64)   256         conv1[0][0]                      
____________________________________________________________________________________________

In [5]:
# Initialize the OpenFace face alignment utility
alignment = AlignDlib('weights/landmarks.dat')

In [6]:
# Funtion to align an image using dlib utility
def align_image(img):
    return alignment.align(96, img, alignment.getLargestFaceBoundingBox(img), 
                           landmarkIndices=AlignDlib.OUTER_EYES_AND_NOSE)

In [7]:
def load_image(path):
    img = cv2.imread(path, 1)
    return img[...,::-1]

In [8]:
class IdentityMetadata():
    def __init__(self, base, name, file):
        self.base = base
        self.name = name
        self.file = file

    def __repr__(self):
        return self.image_path()
    
    def subdir_path(self):
        return self.name
    
    def image_path(self):
        return os.path.join(self.base, self.name, self.file) 
    
def load_metadata(path):
    metadata = []
    for i in sorted(os.listdir(path)):
        for f in sorted(os.listdir(os.path.join(path, i))):
            # Check file extension. Allow only jpg/jpeg' files.
            ext = os.path.splitext(f)[1]
            if ext == '.jpg' or ext == '.jpeg':
                metadata.append(IdentityMetadata(path, i, f))
    return np.array(metadata)

metadata = load_metadata('images')

In [9]:
datagen = ImageDataGenerator(rotation_range=15, 
                             width_shift_range=0.1, 
                             height_shift_range=0.1,
                             shear_range=0.15, 
                             zoom_range=0.1,
                             channel_shift_range = 10, 
                             brightness_range=[0.2,1.0],
                             horizontal_flip=True)
import os

folder_name='AugmentedImages/'
save_here = 'C:/Users/hp/Desktop/aastha/face-recognitition-ams/'+folder_name

if not os.path.exists(save_here):
    os.makedirs(save_here) 
    for i, m in enumerate(metadata): 
        img = load_image(m.image_path())
        datagen.fit(np.expand_dims(img,0))
        directory=save_here+m.subdir_path()
        if not os.path.exists(directory):
            os.makedirs(directory)
            print(directory)
        for x, val in zip(datagen.flow(np.expand_dims(img,0), 
                                       save_to_dir=directory, 
                                       save_prefix='AugImage', 
                                       save_format='jpg'),range(3)) :   
            pass

In [10]:
metadata1 = load_metadata('AugmentedImages')

In [11]:
# To store image embeddings
embedded = np.zeros((metadata1.shape[0], 128))

# Process image through the neural net to get 128 embeddings per image
for i, m in enumerate(metadata1):    
    print(i, " ",m)
    img = load_image(m.image_path())
    img = align_image(img)
    if img is None:
#         print("No face found")
        continue
    # scale RGB values to interval [0,1]
    img = (img / 255.).astype(np.float32)
    # obtain embedding vector for image
    embedded[i] = nn4_small2_pretrained.predict(np.expand_dims(img, axis=0))[0]

0   AugmentedImages\Aastha_Agrawal\AugImage_0_1.jpg

1   AugmentedImages\Aastha_Agrawal\AugImage_0_1128.jpg
2   AugmentedImages\Aastha_Agrawal\AugImage_0_1363.jpg
3   AugmentedImages\Aastha_Agrawal\AugImage_0_1488.jpg
4   AugmentedImages\Aastha_Agrawal\AugImage_0_1551.jpg
5   AugmentedImages\Aastha_Agrawal\AugImage_0_1823.jpg
6   AugmentedImages\Aastha_Agrawal\AugImage_0_1867.jpg
7   AugmentedImages\Aastha_Agrawal\AugImage_0_2014.jpg
8   AugmentedImages\Aastha_Agrawal\AugImage_0_2128.jpg
9   AugmentedImages\Aastha_Agrawal\AugImage_0_2228.jpg
10   AugmentedImages\Aastha_Agrawal\AugImage_0_2264.jpg
11   AugmentedImages\Aastha_Agrawal\AugImage_0_3374.jpg
12   AugmentedImages\Aastha_Agrawal\AugImage_0_3701.jpg
13   AugmentedImages\Aastha_Agrawal\AugImage_0_3725.jpg
14   AugmentedImages\Aastha_Agrawal\AugImage_0_3750.jpg
15   AugmentedImages\Aastha_Agrawal\AugImage_0_4022.jpg
16   AugmentedImages\Aastha_Agrawal\AugImage_0_4131.jpg
17   AugmentedImages\Aastha_Agrawal\AugImage_0_4189.jpg
18  

146   AugmentedImages\Josika_Kar\AugImage_0_7166.jpg
147   AugmentedImages\Josika_Kar\AugImage_0_7320.jpg
148   AugmentedImages\Josika_Kar\AugImage_0_7683.jpg
149   AugmentedImages\Josika_Kar\AugImage_0_7753.jpg
150   AugmentedImages\Josika_Kar\AugImage_0_8366.jpg
151   AugmentedImages\Josika_Kar\AugImage_0_8714.jpg
152   AugmentedImages\Josika_Kar\AugImage_0_9163.jpg
153   AugmentedImages\Josika_Kar\AugImage_0_9188.jpg
154   AugmentedImages\Josika_Kar\AugImage_0_9259.jpg
155   AugmentedImages\Josika_Kar\AugImage_0_9487.jpg


In [12]:
from sklearn.preprocessing import LabelEncoder
targets = np.array([m.name for m in metadata1])
encoder = LabelEncoder()
encoder.fit(targets)

# Numerical encoding of identities
y = encoder.transform(targets)

In [13]:
train_idx = np.arange(metadata1.shape[0]) % 2 != 0
test_idx = np.arange(metadata1.shape[0]) % 2 == 0

# 50 train examples of 10 identities (5 examples each)
X_train = embedded[train_idx]
# 50 test examples of 10 identities (5 examples each)
X_test = embedded[test_idx]

y_train = y[train_idx]
y_test = y[test_idx]

In [14]:
### SUPPORT VECTOR CLASSIFIER
# svc = SVC(kernel="linear", C=0.025) #10 -> 57% accuracy, 30-> 31%, 50->45%
# svc = SVC(gamma=2, C=1, probability=True) #30-> 88%, 50->88%

### Gaussian CLASSIFIER
# svc = GaussianProcessClassifier(1.0 * RBF(1.0)) # 30->90%, 50->89%

### KNN CLASSIFIER
# svc = KNeighborsClassifier(2) #10 images -> 85% accuracy, 30,50 images->88%
# svc = KNeighborsClassifier(5) #10 -> 78% accuracy, 30-> 86%, 50->87%

### DECISION TREE CLASSIFIER
# svc = DecisionTreeClassifier(max_depth=5) # 30,50->58%
# svc = DecisionTreeClassifier(max_depth=10) # 30->68%, 50->79%
# svc = DecisionTreeClassifier(max_depth=20) #30-> 70%, 50->80%
# svc = DecisionTreeClassifier(max_depth=30) # 30->73%, 50->80%
# svc = DecisionTreeClassifier(max_depth=40) # 30->73%, 50->78%

### Random Forest Classifier
# svc = RandomForestClassifier(max_depth=10, n_estimators=50, max_features=1)  #10 -> 80% accuracy aprox, 30,50 -> 88%
# svc = RandomForestClassifier(40)  #10 -> 80% accuracy aprox, 30,50 -> 89%
# svc = RandomForestClassifier(30)  #10 -> 70% accuracy aprox, 30,50 -> 89%
# svc = RandomForestClassifier(20)  #10 -> 65% accuracy aprox, 30,50 -> 87%

### MLP CLASSIFIER
svc = MLPClassifier(alpha=1.0, max_iter=1000) # 30,50->88%

### ADA BOOST CLASSIFIER
# svc = AdaBoostClassifier(n_estimators=100, random_state=0) # 30->35%, 50->28%

### QUADRATIC CLASSIFIER
# svc = QuadraticDiscriminantAnalysis() #30->40%, 50->9%

#Naive bayes algorithm
# svc = GaussianNB() #10 -> 73% accuracy aprox, 30 -> 86%, 50 -> 88%

svc.fit(X_train, y_train)

acc_svc = accuracy_score(y_test, svc.predict(X_test))

print(f'SVM accuracy = {acc_svc}')

SVM accuracy = 1.0


In [15]:
# train_idx = np.arange(metadata.shape[0]) 

# # 50 train examples of 10 identities (5 examples each)
# X_train = embedded[train_idx]

# y_train = y[train_idx]

# # svc = KNeighborsClassifier()
# # svc = SVC()
# svc = RandomForestClassifier(20)
# svc.fit(X_train, y_train)


In [16]:
# Prediction Code for live Images

In [17]:
font = cv2.FONT_HERSHEY_SIMPLEX

def processFrame(img):
    # Change RGB to BGR for imshow
    origImg = img[...,::-1]
    
    # Get bounding box
    bb = alignment.getLargestFaceBoundingBox(img)
    
    # Align image
    img = align_image(img)
    
    # scale RGB values to interval [0,1]
    img = (img / 255.).astype(np.float32)
    
    # obtain embedding vector for image
    features = nn4_small2_pretrained.predict(np.expand_dims(img, axis=0))[0]
    
    # Get the class for prediction
    predClass = svc.predict([features])
    predClass = encoder.inverse_transform(predClass)[0]
    
    # Display the image with bounding box & label
    cv2.putText(origImg,predClass,(bb.left(),bb.top()-5), font, 0.5, (0,0,255), 1, cv2.LINE_AA)
    cv2.rectangle(origImg,(bb.left(),bb.top()),(bb.right(),bb.bottom()),(0,0,255),2)
    cv2.imshow('image',origImg)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [18]:
font = cv2.FONT_HERSHEY_SIMPLEX

def processFrame1(img):
    # Change RGB to BGR for imshow
    origImg = img[...,::-1]
    
    # Get bounding box
    bb = alignment.getLargestFaceBoundingBox(img)
    
    # Align image
    img = align_image(img)
    
    # scale RGB values to interval [0,1]
    img = (img / 255.).astype(np.float32)
    
    # obtain embedding vector for image
    features = nn4_small2_pretrained.predict(np.expand_dims(img, axis=0))[0]
    
    # Get the class for prediction
    predScores = svc.predict_proba([features])
    print(predScores)
    predClass = None
    
    maxProb = (predScores[0]).max()
    
    print(maxProb)
    
    if(maxProb >= 0.8):
    
        predClass = [(predScores[0]).argmax()]
        print(predClass)
        predClass = encoder.inverse_transform(predClass)[0]
    
    
    print(predClass)
    
    return bb, predClass

In [19]:
students = []

cap = cv2.VideoCapture(0)
counter = 0
studentList = []
while(True):
    counter+=1
    # Capture frame-by-frame
    ret, frame = cap.read()
#     print(ret, " ", frame)
    if frame is not None:  
        if(alignment.getLargestFaceBoundingBox(frame)!=None):
            bb, predClass = processFrame1(frame)
            print("oo: ",predClass)
            studentList.append(predClass)
            cv2.rectangle(frame,(bb.left(),bb.top()),(bb.right(),bb.bottom()),(0,0,255),2)
            if counter==10:
                predClass = str(max(set(studentList), key = studentList.count)) 
                if predClass != 'None':
                    if predClass not in students:
                          students.append(predClass)
                    cv2.putText(frame,predClass,(bb.left(),bb.top()-5), font, 0.5, (0,0,255), 1, cv2.LINE_AA)
                counter = 0
                studentList = []
#             if(predClass!=None):
#                 cv2.putText(frame,predClass,(bb.left(),bb.top()-5), font, 0.5, (0,0,255), 1, cv2.LINE_AA)
#                 if predClass not in students:
#                     students.append(predClass)
            cv2.imshow('frame',frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
print(students)

[[0.56962057 0.075899   0.07792492 0.27655551]]
0.569620569946773
None
oo:  None
[[0.59028571 0.07384706 0.04433968 0.29152755]]
0.5902857120681114
None
oo:  None
[[0.79912137 0.02947062 0.04783386 0.12357414]]
0.7991213718725892
None
oo:  None
[[0.71204153 0.05199305 0.05016112 0.1858043 ]]
0.712041530822867
None
oo:  None
[[0.94018578 0.00560579 0.04014078 0.01406766]]
0.9401857768290675
[0]
Aastha_Agrawal
oo:  Aastha_Agrawal
[[0.92731996 0.00839404 0.0462926  0.0179934 ]]
0.9273199603870099
[0]
Aastha_Agrawal
oo:  Aastha_Agrawal
[[0.92929047 0.00988366 0.0297175  0.03110838]]
0.929290470899776
[0]
Aastha_Agrawal
oo:  Aastha_Agrawal
[[0.93563029 0.00911503 0.03549139 0.0197633 ]]
0.9356302854737009
[0]
Aastha_Agrawal
oo:  Aastha_Agrawal
[[0.92514442 0.00881921 0.04785685 0.01817951]]
0.9251444228367631
[0]
Aastha_Agrawal
oo:  Aastha_Agrawal
[[0.92231419 0.01009619 0.04789386 0.01969576]]
0.9223141887388808
[0]
Aastha_Agrawal
oo:  Aastha_Agrawal
[[0.92629319 0.00985238 0.03362385 0.03